apiVersion: v1
kind: Service
metadata:
  name: encurtador-service
spec:
  selector:
    app: encurtador-url
  ports:
    - protocol: TCP
      port: 8081        
      targetPort: 8000    
  type: LoadBalancer
